version: '2'
services:
  kibana:
    image: docker.elastic.co/kibana/kibana:6.1.1
    container_name: kibana-image
    restart: always
    network_mode: host
    environment:
      - env=${environment}
    extra_hosts:
      - "elasticsearchHost:${K_ELASTICSEARCH_HOST_IP}"
    ports:
      - "5601:5601"
    volumes:
      - ./config/kibana.yml:/etc/kibana/kibana.yml
    logging:
      driver: json-file
      options:
        max-file: '5'
        max-size: 10m
